# Generated by Django 4.0.1 on 2022-02-04 09:34

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
